version: '2'
services:
  mongo_host:
    image: mongo:latest
    restart: always
    ports: ["27018:27017"]
  postgres_host:
    image: postgres:10-alpine
    restart: always
    ports: ["5433:5432"]
  python-db:
    build:
      context: .
    depends_on:
      - mongo_host
      - postgres_host
    tty: true
    environment:
      - APP_MONGO_HOST=mongo_host
      - APP_MONGO_PORT=27017
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
    volumes:
      - /tmp/data:/data
    links: [mongo_host, postgres_host]