version: '2'
services:
  mongo_host:
    image: mongo:3.4.4
    restart: always
    ports: ["27017:27017"]
  mongo-client:
    build:
      context: .
    depends_on:
      - mongo_host
    tty: true
    environment:
      - APP_MONGO_HOST=mongo_host
      - APP_MONGO_PORT=27017
    volumes:
      - /tmp/data:/data
    links: [mongo_host]
